name: Run robot tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-rf:
    name: Build docker image and start tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t robot-browser .

      - name: Create folder for reports
        run: mkdir -p ${{ github.workspace }}/reports

      - name: Run robot tests
        run: |
          docker run --name "robot-tests" \
            robot-browser \
              bash -c "robot -i demo --outputdir /robot/output /robot"

      - name: Retrieve test results from docker container
        if: always()
        run: docker cp robot-tests:/robot/output/. ${{ github.workspace }}/reports/

      - name: upload tests results as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: ${{ github.workspace }}/reports
