name: Run robot tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-rf:
    name: Build docker image and start tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t robot-browser .

      - name: Run robot tests
        run: |
          docker run robot-browser bash -c "robot --outputdir /robot/output /robot"

      - name: list containers
        if: always()
        run: docker ps

      - name: Retrieve test results from docker container
        if: always()
        run: docker cp robot-browser:/robot/output/. ${{ github.workspace }}/reports/

      - name: upload tests results as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: ${{ github.workspace }}/reports
